# Generated by Django 4.2.5 on 2023-09-20 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=50)),
                ('UF', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('carga_horaria_total', models.CharField(max_length=50)),
                ('duracao', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('site', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ocupacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Professor', models.CharField(max_length=50)),
                ('Estudante', models.CharField(max_length=50)),
                ('Coordenador', models.CharField(max_length=50)),
                ('Diretor', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Periodos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Saber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tipos_avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prova', models.CharField(max_length=50)),
                ('Trabalho', models.CharField(max_length=50)),
                ('projeto', models.CharField(max_length=50)),
                ('lista', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Turmas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Periodos', models.CharField(max_length=50)),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('pai', models.CharField(max_length=50)),
                ('mae', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=50)),
                ('data_nasc', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('Cidades', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cidades')),
            ],
        ),
        migrations.CreateModel(
            name='Ocorrencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descricao', models.CharField(max_length=50)),
                ('data', models.CharField(max_length=50)),
                ('Cursos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cursos')),
                ('Diciplinas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.disciplinas')),
                ('Pessoas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pessoas')),
            ],
        ),
        migrations.CreateModel(
            name='Matriculas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data_inicio', models.CharField(max_length=50)),
                ('Data_previsao_terminio', models.CharField(max_length=50)),
                ('Cursos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cursos')),
                ('Instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.instituicao')),
                ('Pessoas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pessoas')),
            ],
        ),
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Faltas', models.CharField(max_length=50)),
                ('Cursos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cursos')),
                ('Diciplinas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.disciplinas')),
            ],
        ),
        migrations.CreateModel(
            name='Disciplinas_Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=50)),
                ('Carga_Horaria', models.CharField(max_length=50)),
                ('Cursos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cursos')),
                ('Periodos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.periodos')),
            ],
        ),
        migrations.AddField(
            model_name='disciplinas',
            name='Saber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.saber'),
        ),
        migrations.AddField(
            model_name='cursos',
            name='Instituicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.instituicao'),
        ),
        migrations.AddField(
            model_name='cursos',
            name='saber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.saber'),
        ),
        migrations.CreateModel(
            name='Avaliacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descricao', models.CharField(max_length=50)),
                ('Cursos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cursos')),
                ('Diciplinas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.disciplinas')),
            ],
        ),
    ]
